using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Hexprite.Core;

namespace Hexprite.Services
{
    /// <summary>
    /// Service that converts a FontDocument into various C-style export formats.
    /// Supports Adafruit GFX, LVGL, u8g2 BDF, and Raw C Array.
    /// </summary>
    public class FontCodeGeneratorService : IFontCodeGeneratorService
    {
        /// <summary>
        /// Sanitizes a font identifier for C/C++ usage, defaulting to "myFont" if empty.
        /// </summary>
        public static string SanitiseFontName(string? name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "myFont";
            string sanitised = CodeGeneratorService.SanitiseName(name);
            return sanitised == "sprite" ? "myFont" : sanitised;
        }

        /// <summary>
        /// Converts a character into a safe, human-readable display string for C comments,
        /// avoiding raw newlines or unescaped quotes that break C comment line syntax.
        /// </summary>
        public static string GetPrintableCharDisplay(char c)
        {
            if (c == '\'') return "\\'";
            if (c == '\\') return "\\\\";
            if (char.IsControl(c) || char.IsWhiteSpace(c))
            {
                return c switch
                {
                    ' ' => "space",
                    '\t' => "\\t",
                    '\n' => "\\n",
                    '\r' => "\\r",
                    '\0' => "\\0",
                    _ => string.Create(CultureInfo.InvariantCulture, $"0x{(int)c:X2}")
                };
            }
            return c.ToString(CultureInfo.InvariantCulture);
        }

        public string GenerateCode(FontDocument doc, FontExportSettings settings)
        {
            ArgumentNullException.ThrowIfNull(doc);
            ArgumentNullException.ThrowIfNull(settings);

            // Ensure glyphs are always processed in ascending order of code point
            var sortedGlyphs = doc.Glyphs != null
                ? doc.Glyphs.Where(g => g != null).OrderBy(g => g.CodePoint).ToList()
                : [];

            return settings.Format switch
            {
                FontExportFormat.AdafruitGfx => GenerateAdafruitGfx(doc, settings, sortedGlyphs),
                FontExportFormat.U8g2Bdf     => GenerateU8g2Bdf(doc, settings, sortedGlyphs),
                FontExportFormat.Lvgl        => GenerateLvgl(doc, settings, sortedGlyphs),
                FontExportFormat.RawCArray   => GenerateRawCArray(doc, settings, sortedGlyphs),
                FontExportFormat.FlipperZero => GenerateFlipperZero(doc, settings, sortedGlyphs),
                _ => throw new NotSupportedException($"Font format {settings.Format} is not supported."),
            };
        }

        private static List<GlyphState> EnsureContiguousGlyphs(FontDocument doc, List<GlyphState> glyphs)
        {
            if (doc.FirstChar > doc.LastChar) return glyphs;

            var glyphLookup = new Dictionary<int, GlyphState>(glyphs.Count);
            foreach (var g in glyphs)
            {
                glyphLookup[g.CodePoint] = g;
            }

            var contiguous = new List<GlyphState>(doc.LastChar - doc.FirstChar + 1);
            for (int cp = doc.FirstChar; cp <= doc.LastChar; cp++)
            {
                if (glyphLookup.TryGetValue(cp, out var g))
                {
                    contiguous.Add(g);
                }
                else
                {
                    contiguous.Add(new GlyphState
                    {
                        CodePoint = cp,
                        Width = 0,
                        Height = 0,
                        XAdvance = 0,
                        XOffset = 0,
                        YOffset = 0,
                        Pixels = [],
                    });
                }
            }

            return contiguous;
        }

        private static string GenerateAdafruitGfx(FontDocument doc, FontExportSettings settings, List<GlyphState> glyphs)
        {
            glyphs = EnsureContiguousGlyphs(doc, glyphs);
            var sb = new StringBuilder();
            string name = SanitiseFontName(settings.FontName);
            string hexFmt = settings.UppercaseHex ? "X2" : "x2";

            sb.AppendLine("// ----------------------------------------------------------------------------");
            sb.AppendLine(CultureInfo.InvariantCulture, $"// Adafruit GFX Font: {name}");
            sb.AppendLine("// Generated by Hexprite - Embedded Pixel Art & Font Editor");
            sb.AppendLine(CultureInfo.InvariantCulture, $"// Dimensions: {doc.MaxCellWidth}x{doc.CellHeight} px | Range: 0x{doc.FirstChar:X2} - 0x{doc.LastChar:X2} | Baseline: {doc.Baseline} px | Y-Advance: {doc.YAdvance} px");
            sb.AppendLine("// ----------------------------------------------------------------------------");

            if (settings.IncludeUsageComment)
            {
                sb.AppendLine("// USAGE GUIDE:");
                sb.AppendLine("// 1. Include this header in your Arduino / PlatformIO sketch:");
                sb.AppendLine(CultureInfo.InvariantCulture, $"//    #include \"{name}.h\"");
                sb.AppendLine("// 2. Set the font on your Adafruit GFX display object:");
                sb.AppendLine(CultureInfo.InvariantCulture, $"//    display.setFont(&{name});");
                sb.AppendLine("// 3. Position the cursor and print text:");
                sb.AppendLine("//    // NOTE: Adafruit GFX custom fonts draw relative to the BASELINE (not top-left).");
                sb.AppendLine(CultureInfo.InvariantCulture, $"//    display.setCursor(0, {doc.Baseline}); // First line sits at y={doc.Baseline}");
                sb.AppendLine("//    display.setTextColor(WHITE);");
                sb.AppendLine("//    display.print(\"Hello World\");");
                sb.AppendLine();
            }

            sb.AppendLine("#pragma once");
            sb.AppendLine("#include <stdint.h>");
            sb.AppendLine("#if defined(ARDUINO)");
            sb.AppendLine("  #include <Arduino.h>");
            sb.AppendLine("  #include <Adafruit_GFX.h>");
            sb.AppendLine("#else");
            sb.AppendLine("  #include <gfxfont.h>");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // 1. Bitmaps array
            sb.AppendLine(CultureInfo.InvariantCulture, $"const uint8_t {name}Bitmaps[] PROGMEM = {{");

            var glyphRecords = new List<GlyphRecord>();
            int currentOffset = 0;

            for (int i = 0; i < glyphs.Count; i++)
            {
                var glyph = glyphs[i];
                var (cx, cy, cw, ch) = glyph.GetTightBounds();
                var cropped = glyph.GetCroppedPixels();

                int glyphXOffset = glyph.XOffset + cx;
                int glyphYOffset = (cy - doc.Baseline) + glyph.YOffset;
                string charDisp = GetPrintableCharDisplay(glyph.Character);

                if (settings.IncludeGlyphPreview && settings.IncludeMetricComments)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture, $"  // @{currentOffset} '{charDisp}' (0x{glyph.CodePoint:X2}) {cw}x{ch}");
                }
                else if (settings.IncludeMetricComments)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture, $"  // '{charDisp}' (0x{glyph.CodePoint:X2})");
                }

                if (settings.IncludeGlyphPreview)
                {
                    AppendAsciiPreview(sb, cropped, cw, ch, "  // ");
                }

                // Pack bits (row major, bit packed)
                if (cw > 0 && ch > 0)
                {
                    sb.Append("  ");
                    int bitCount = 0;
                    byte currentByte = 0;
                    int bytesOnLine = 0;

                    for (int y = 0; y < ch; y++)
                    {
                        for (int x = 0; x < cw; x++)
                        {
                            if (cropped[y * cw + x])
                            {
                                currentByte |= (byte)(1 << (7 - bitCount));
                            }
                            bitCount++;

                            if (bitCount == 8)
                            {
                                sb.Append(CultureInfo.InvariantCulture, $"0x{currentByte.ToString(hexFmt, CultureInfo.InvariantCulture)}, ");
                                currentByte = 0;
                                bitCount = 0;
                                bytesOnLine++;
                                if (bytesOnLine >= 12)
                                {
                                    sb.AppendLine();
                                    sb.Append("  ");
                                    bytesOnLine = 0;
                                }
                            }
                        }
                    }

                    if (bitCount > 0)
                    {
                        sb.Append(CultureInfo.InvariantCulture, $"0x{currentByte.ToString(hexFmt, CultureInfo.InvariantCulture)}, ");
                    }
                    sb.AppendLine();
                }

                glyphRecords.Add(new GlyphRecord
                {
                    Offset = currentOffset,
                    Width = cw,
                    Height = ch,
                    XAdvance = glyph.XAdvance,
                    XOffset = glyphXOffset,
                    YOffset = glyphYOffset,
                });

                int bytesUsed = (cw * ch + 7) / 8;
                currentOffset += bytesUsed;
            }

            sb.AppendLine("};");
            sb.AppendLine();

            // 2. Glyphs array
            sb.AppendLine(CultureInfo.InvariantCulture, $"const GFXglyph {name}Glyphs[] PROGMEM = {{");
            for (int i = 0; i < glyphs.Count; i++)
            {
                var r = glyphRecords[i];
                var glyph = glyphs[i];
                sb.Append(CultureInfo.InvariantCulture, $"  {{ {r.Offset,5}, {r.Width,3}, {r.Height,3}, {r.XAdvance,3}, {r.XOffset,3}, {r.YOffset,3} }}");
                if (i < glyphs.Count - 1) sb.Append(',');
                else sb.Append(' ');

                if (settings.IncludeMetricComments)
                {
                    sb.Append(CultureInfo.InvariantCulture, $" // 0x{glyph.CodePoint:X2} '{GetPrintableCharDisplay(glyph.Character)}'");
                }
                sb.AppendLine();
            }
            sb.AppendLine("};");
            sb.AppendLine();

            // 3. Font struct
            sb.AppendLine(CultureInfo.InvariantCulture, $"const GFXfont {name} PROGMEM = {{");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  (uint8_t  *){name}Bitmaps,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  (GFXglyph *){name}Glyphs,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  0x{doc.FirstChar:X2}, 0x{doc.LastChar:X2}, {doc.YAdvance}");
            sb.AppendLine("};");

            return sb.ToString();
        }

        private static string GenerateU8g2Bdf(FontDocument doc, FontExportSettings settings, List<GlyphState> glyphs)
        {
            var sb = new StringBuilder();
            string name = SanitiseFontName(settings.FontName);

            sb.AppendLine("STARTFONT 2.1");
            sb.AppendLine("COMMENT ----------------------------------------------------------------------------");
            sb.AppendLine(CultureInfo.InvariantCulture, $"COMMENT U8g2 BDF Font: {name}");
            sb.AppendLine("COMMENT Generated by Hexprite - Embedded Pixel Art & Font Editor");
            sb.AppendLine(CultureInfo.InvariantCulture, $"COMMENT Dimensions: {doc.MaxCellWidth}x{doc.CellHeight} px | Range: 0x{doc.FirstChar:X2} - 0x{doc.LastChar:X2} | Baseline: {doc.Baseline} px");
            sb.AppendLine("COMMENT ----------------------------------------------------------------------------");
            sb.AppendLine("COMMENT TO USE WITH U8G2:");
            sb.AppendLine("COMMENT 1. Convert this .bdf file to a u8g2 C source array using bdfconv:");
            sb.AppendLine(CultureInfo.InvariantCulture, $"COMMENT    bdfconv.exe -v -f 1 -m \"{doc.FirstChar}-{doc.LastChar}\" {name}.bdf -o {name}.c -n u8g2_font_{name}");
            sb.AppendLine("COMMENT 2. In your Arduino / PlatformIO sketch:");
            sb.AppendLine(CultureInfo.InvariantCulture, $"COMMENT    extern const uint8_t u8g2_font_{name}[] U8G2_FONT_SECTION(\"u8g2_font_{name}\");");
            sb.AppendLine(CultureInfo.InvariantCulture, $"COMMENT    u8g2.setFont(u8g2_font_{name});");
            sb.AppendLine(CultureInfo.InvariantCulture, $"COMMENT    u8g2.drawStr(0, {doc.Baseline}, \"Hello World\");");
            sb.AppendLine("COMMENT ----------------------------------------------------------------------------");
            sb.AppendLine(CultureInfo.InvariantCulture, $"FONT -hexprite-{name}-medium-r-normal--{doc.CellHeight}-{doc.CellHeight}0-75-75-c-{doc.MaxCellWidth}0-iso10646-1");
            sb.AppendLine(CultureInfo.InvariantCulture, $"SIZE {doc.CellHeight} 75 75");

            int fontBbxY = Math.Min(0, -doc.Descent);
            sb.AppendLine(CultureInfo.InvariantCulture, $"FONTBOUNDINGBOX {doc.MaxCellWidth} {doc.CellHeight} 0 {fontBbxY}");

            sb.AppendLine("STARTPROPERTIES 2");
            sb.AppendLine(CultureInfo.InvariantCulture, $"FONT_ASCENT {doc.Baseline}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"FONT_DESCENT {doc.Descent}");
            sb.AppendLine("ENDPROPERTIES");

            sb.AppendLine(CultureInfo.InvariantCulture, $"CHARS {glyphs.Count}");

            foreach (var glyph in glyphs)
            {
                var (cx, cy, cw, ch) = glyph.GetTightBounds();
                var cropped = glyph.GetCroppedPixels();

                int bbx_x = glyph.XOffset + cx;
                int bbx_y = (cw > 0 && ch > 0) ? (doc.Baseline - cy - ch - glyph.YOffset) : 0;

                string charName;
                if (char.IsWhiteSpace(glyph.Character) || char.IsControl(glyph.Character))
                {
                    charName = glyph.CodePoint == 32 ? "space" : string.Create(CultureInfo.InvariantCulture, $"char_{glyph.CodePoint}");
                }
                else
                {
                    charName = glyph.Character.ToString(CultureInfo.InvariantCulture);
                }

                sb.AppendLine(CultureInfo.InvariantCulture, $"STARTCHAR {charName}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"ENCODING {glyph.CodePoint}");
                // SWIDTH = (XAdvance * 1000) / CellHeight (approx)
                int swidth = doc.CellHeight > 0 ? (int)(glyph.XAdvance * 1000.0 / doc.CellHeight) : glyph.XAdvance * 100;
                sb.AppendLine(CultureInfo.InvariantCulture, $"SWIDTH {swidth} 0");
                sb.AppendLine(CultureInfo.InvariantCulture, $"DWIDTH {glyph.XAdvance} 0");
                sb.AppendLine(CultureInfo.InvariantCulture, $"BBX {cw} {ch} {bbx_x} {bbx_y}");
                sb.AppendLine("BITMAP");

                for (int y = 0; y < ch; y++)
                {
                    int bytesPerRow = (cw + 7) / 8;
                    for (int chunk = 0; chunk < bytesPerRow; chunk++)
                    {
                        byte currentByte = 0;
                        for (int bit = 0; bit < 8; bit++)
                        {
                            int px = chunk * 8 + bit;
                            if (px < cw && cropped[y * cw + px])
                            {
                                currentByte |= (byte)(1 << (7 - bit));
                            }
                        }
                        sb.Append(CultureInfo.InvariantCulture, $"{currentByte:X2}");
                    }
                    sb.AppendLine();
                }
                sb.AppendLine("ENDCHAR");
            }

            sb.AppendLine("ENDFONT");
            return sb.ToString();
        }

        private static string GenerateLvgl(FontDocument doc, FontExportSettings settings, List<GlyphState> glyphs)
        {
            var sb = new StringBuilder();
            string name = SanitiseFontName(settings.FontName);
            string hexFmt = settings.UppercaseHex ? "X2" : "x2";

            sb.AppendLine("/* ----------------------------------------------------------------------------");
            sb.AppendLine(CultureInfo.InvariantCulture, $" * LVGL Font: {name}");
            sb.AppendLine(" * Generated by Hexprite - Embedded Pixel Art & Font Editor");
            sb.AppendLine(CultureInfo.InvariantCulture, $" * Dimensions: {doc.MaxCellWidth}x{doc.CellHeight} px | Range: 0x{doc.FirstChar:X4} - 0x{doc.LastChar:X4} | Baseline: {doc.Baseline} px | Line Height: {doc.YAdvance} px");
            sb.AppendLine(" * ----------------------------------------------------------------------------");

            if (settings.IncludeUsageComment)
            {
                sb.AppendLine(" * USAGE GUIDE:");
                sb.AppendLine(" * 1. Declare the font in your C/C++ source or header:");
                sb.AppendLine(CultureInfo.InvariantCulture, $" *    LV_FONT_DECLARE({name});");
                sb.AppendLine(" * 2. Set the font on an LVGL object (v8 / v9):");
                sb.AppendLine(CultureInfo.InvariantCulture, $" *    lv_obj_set_style_text_font(label, &{name}, 0);");
                sb.AppendLine(" * ---------------------------------------------------------------------------- */");
                sb.AppendLine();
            }
            else
            {
                sb.AppendLine(" * ---------------------------------------------------------------------------- */");
                sb.AppendLine();
            }

            sb.AppendLine("#pragma once");
            sb.AppendLine("#if defined(LV_LVGL_H_INCLUDE_SIMPLE)");
            sb.AppendLine("  #include \"lvgl.h\"");
            sb.AppendLine("#else");
            sb.AppendLine("  #include \"lvgl/lvgl.h\"");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // 1. Bitmaps
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_glyph_bitmap[] = {{");

            int currentOffset = 0;
            var glyphRecords = new List<GlyphRecord>();

            for (int i = 0; i < glyphs.Count; i++)
            {
                var glyph = glyphs[i];
                var (cx, cy, cw, ch) = glyph.GetTightBounds();
                var cropped = glyph.GetCroppedPixels();

                int glyphXOffset = glyph.XOffset + cx;
                int glyphYOffset = (cy - doc.Baseline) + glyph.YOffset;
                string charDisp = GetPrintableCharDisplay(glyph.Character);

                if (settings.IncludeMetricComments)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture, $"  /* '{charDisp}' (0x{glyph.CodePoint:X2}) */");
                }
                if (settings.IncludeGlyphPreview)
                {
                    AppendAsciiPreview(sb, cropped, cw, ch, "  /* ", " */");
                }

                if (cw > 0 && ch > 0)
                {
                    sb.Append("  ");
                    int bytesOnLine = 0;
                    int bitCount = 0;
                    byte currentByte = 0;

                    for (int y = 0; y < ch; y++)
                    {
                        for (int x = 0; x < cw; x++)
                        {
                            if (cropped[y * cw + x])
                            {
                                currentByte |= (byte)(1 << (7 - bitCount));
                            }
                            bitCount++;
                            if (bitCount == 8)
                            {
                                sb.Append(CultureInfo.InvariantCulture, $"0x{currentByte.ToString(hexFmt, CultureInfo.InvariantCulture)}, ");
                                bytesOnLine++;
                                if (bytesOnLine >= 12)
                                {
                                    sb.AppendLine();
                                    sb.Append("  ");
                                    bytesOnLine = 0;
                                }
                                currentByte = 0;
                                bitCount = 0;
                            }
                        }
                    }

                    if (bitCount > 0)
                    {
                        sb.Append(CultureInfo.InvariantCulture, $"0x{currentByte.ToString(hexFmt, CultureInfo.InvariantCulture)}, ");
                        bytesOnLine++;
                    }

                    if (bytesOnLine > 0) sb.AppendLine();
                }

                glyphRecords.Add(new GlyphRecord
                {
                    Offset = currentOffset,
                    Width = cw,
                    Height = ch,
                    XAdvance = glyph.XAdvance,
                    XOffset = glyphXOffset,
                    YOffset = glyphYOffset,
                });

                int bytesUsed = (cw * ch + 7) / 8;
                currentOffset += bytesUsed;
            }

            sb.AppendLine("};");
            sb.AppendLine();

            // 2. Glyph descriptors
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const lv_font_fmt_txt_glyph_dsc_t {name}_glyph_dsc[] = {{");
            // Reserved dummy missing glyph at index 0 (standard LVGL sentinel)
            sb.AppendLine("  { .bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0 }, /* Reserved missing glyph */");
            for (int i = 0; i < glyphs.Count; i++)
            {
                var r = glyphRecords[i];
                var glyph = glyphs[i];
                // In LVGL: ofs_y is the distance from baseline to the BOTTOM of the bounding box (positive UP)
                int ofs_y = -r.YOffset - r.Height;
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {{ .bitmap_index = {r.Offset}, .adv_w = {r.XAdvance * 16}, .box_w = {r.Width}, .box_h = {r.Height}, .ofs_x = {r.XOffset}, .ofs_y = {ofs_y} }}, /* '{GetPrintableCharDisplay(glyph.Character)}' */");
            }
            sb.AppendLine("};");
            sb.AppendLine();

            // 3. CMAP
            bool isContiguous = true;
            for (int i = 0; i < glyphs.Count; i++)
            {
                if (glyphs[i].CodePoint != doc.FirstChar + i)
                {
                    isContiguous = false;
                    break;
                }
            }

            int rangeLength = glyphs.Count > 0 ? (doc.LastChar - doc.FirstChar + 1) : 0;

            if (!isContiguous)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint16_t {name}_unicode_list[] = {{");
                sb.Append("  ");
                for (int i = 0; i < glyphs.Count; i++)
                {
                    // LVGL SPARSE_TINY stores relative offsets from range_start (doc.FirstChar)
                    uint relativeOffset = (uint)Math.Max(0, glyphs[i].CodePoint - doc.FirstChar);
                    sb.Append(CultureInfo.InvariantCulture, $"0x{relativeOffset:X4}, ");
                }
                sb.AppendLine("\n};");
                sb.AppendLine();

                sb.AppendLine(CultureInfo.InvariantCulture, $"static const lv_font_fmt_txt_cmap_t {name}_cmap[] = {{");
                sb.AppendLine("  {");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    .range_start = 0x{doc.FirstChar:X4},");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    .range_length = {rangeLength},");
                sb.AppendLine("    .glyph_id_start = 1,"); // Points to index 1 in glyph_dsc (skipping dummy glyph 0)
                sb.AppendLine(CultureInfo.InvariantCulture, $"    .unicode_list = {name}_unicode_list,");
                sb.AppendLine("    .glyph_id_ofs_list = NULL,");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    .list_length = {glyphs.Count},");
                sb.AppendLine("    .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY");
                sb.AppendLine("  }");
                sb.AppendLine("};");
                sb.AppendLine();
            }
            else
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"static const lv_font_fmt_txt_cmap_t {name}_cmap[] = {{");
                sb.AppendLine("  {");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    .range_start = 0x{doc.FirstChar:X4},");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    .range_length = {rangeLength},");
                sb.AppendLine("    .glyph_id_start = 1,"); // Points to index 1 in glyph_dsc (skipping dummy glyph 0)
                sb.AppendLine("    .unicode_list = NULL,");
                sb.AppendLine("    .glyph_id_ofs_list = NULL,");
                sb.AppendLine("    .list_length = 0,");
                sb.AppendLine("    .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY");
                sb.AppendLine("  }");
                sb.AppendLine("};");
                sb.AppendLine();
            }

            // 4. Font object
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const lv_font_fmt_txt_dsc_t {name}_font_dsc = {{");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .glyph_bitmap = {name}_glyph_bitmap,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .glyph_dsc = {name}_glyph_dsc,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .cmaps = {name}_cmap,");
            sb.AppendLine("  .kern_dsc = NULL,");
            sb.AppendLine("  .kern_scale = 0,");
            sb.AppendLine("  .cmap_num = 1,");
            sb.AppendLine("  .bpp = 1,");
            sb.AppendLine("  .kern_classes = 0,");
            sb.AppendLine("  .bitmap_format = 0");
            sb.AppendLine("};");
            sb.AppendLine();

            sb.AppendLine(CultureInfo.InvariantCulture, $"const lv_font_t {name} = {{");
            sb.AppendLine("  .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,");
            sb.AppendLine("  .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .line_height = {doc.YAdvance},");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .base_line = -({Math.Max(0, doc.CellHeight - doc.Baseline)}),");
            sb.AppendLine("  .subpx = LV_FONT_SUBPX_NONE,");
            sb.AppendLine("  .underline_position = -1,");
            sb.AppendLine("  .underline_thickness = 1,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .dsc = &{name}_font_dsc");
            sb.AppendLine("};");

            return sb.ToString();
        }

        private static string GenerateRawCArray(FontDocument doc, FontExportSettings settings, List<GlyphState> glyphs)
        {
            glyphs = EnsureContiguousGlyphs(doc, glyphs);
            var sb = new StringBuilder();
            string name = SanitiseFontName(settings.FontName);
            string hexFmt = settings.UppercaseHex ? "X2" : "x2";

            sb.AppendLine("// ----------------------------------------------------------------------------");
            sb.AppendLine(CultureInfo.InvariantCulture, $"// Raw C Array Font: {name}");
            sb.AppendLine("// Generated by Hexprite - Embedded Pixel Art & Font Editor");
            sb.AppendLine(CultureInfo.InvariantCulture, $"// Dimensions: {doc.MaxCellWidth}x{doc.CellHeight} px | Range: 0x{doc.FirstChar:X2} - 0x{doc.LastChar:X2} | Baseline: {doc.Baseline} px | Y-Advance: {doc.YAdvance} px");
            sb.AppendLine("// ----------------------------------------------------------------------------");

            if (settings.IncludeUsageComment)
            {
                sb.AppendLine("// USAGE GUIDE:");
                sb.AppendLine("// Each glyph bitmap is stored row-major with bit packing (MSB first).");
                sb.AppendLine(CultureInfo.InvariantCulture, $"// Access glyph data via {name}_bitmaps[c - 0x{doc.FirstChar:X2}] and metrics via {name}_font.");
                sb.AppendLine();
            }

            sb.AppendLine("#pragma once");
            sb.AppendLine("#include <stdint.h>");
            sb.AppendLine("#include <stdbool.h>");
            sb.AppendLine();

            var glyphRecords = new List<GlyphRecord>();

            foreach (var glyph in glyphs)
            {
                var (cx, cy, cw, ch) = glyph.GetTightBounds();
                var cropped = glyph.GetCroppedPixels();

                int glyphXOffset = glyph.XOffset + cx;
                int glyphYOffset = (cy - doc.Baseline) + glyph.YOffset;

                glyphRecords.Add(new GlyphRecord
                {
                    Offset = 0,
                    Width = cw,
                    Height = ch,
                    XAdvance = glyph.XAdvance,
                    XOffset = glyphXOffset,
                    YOffset = glyphYOffset,
                });

                if (settings.IncludeMetricComments)
                {
                    string charDisp = GetPrintableCharDisplay(glyph.Character);
                    sb.AppendLine(CultureInfo.InvariantCulture, $"// '{charDisp}' (0x{glyph.CodePoint:X2})");
                    sb.AppendLine(CultureInfo.InvariantCulture, $"// Width: {cw}, Height: {ch}, XAdvance: {glyph.XAdvance}, XOffset: {glyphXOffset}, YOffset: {glyphYOffset}");
                }
                if (settings.IncludeGlyphPreview)
                {
                    AppendAsciiPreview(sb, cropped, cw, ch, "// ");
                }

                if (cw > 0 && ch > 0)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_{glyph.CodePoint:X2}[] = {{");
                    sb.Append("  ");
                    int bytesOnLine = 0;
                    for (int y = 0; y < ch; y++)
                    {
                        int bytesPerRow = (cw + 7) / 8;
                        for (int chunk = 0; chunk < bytesPerRow; chunk++)
                        {
                            byte currentByte = 0;
                            for (int bit = 0; bit < 8; bit++)
                            {
                                int px = chunk * 8 + bit;
                                if (px < cw && cropped[y * cw + px])
                                {
                                    currentByte |= (byte)(1 << (7 - bit));
                                }
                            }
                            sb.Append(CultureInfo.InvariantCulture, $"0x{currentByte.ToString(hexFmt, CultureInfo.InvariantCulture)}, ");
                            bytesOnLine++;
                            if (bytesOnLine >= 12)
                            {
                                sb.AppendLine();
                                sb.Append("  ");
                                bytesOnLine = 0;
                            }
                        }
                    }
                    if (bytesOnLine > 0) sb.AppendLine();
                    sb.AppendLine("};");
                }
                else
                {
                    sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_{glyph.CodePoint:X2}[] = {{ 0x00 }};");
                }
                sb.AppendLine();
            }

            // Bitmaps pointer array
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t* const {name}_bitmaps[] = {{");
            for (int i = 0; i < glyphs.Count; i++)
            {
                var glyph = glyphs[i];
                sb.Append(CultureInfo.InvariantCulture, $"  {name}_{glyph.CodePoint:X2}");
                if (i < glyphs.Count - 1) sb.Append(',');
                sb.AppendLine(CultureInfo.InvariantCulture, $" // 0x{glyph.CodePoint:X2} '{GetPrintableCharDisplay(glyph.Character)}'");
            }
            sb.AppendLine("};");
            sb.AppendLine();

            // Metric arrays
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_widths[] = {{ {string.Join(", ", glyphRecords.ConvertAll(r => r.Width.ToString(CultureInfo.InvariantCulture)))} }};");
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_heights[] = {{ {string.Join(", ", glyphRecords.ConvertAll(r => r.Height.ToString(CultureInfo.InvariantCulture)))} }};");
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_advances[] = {{ {string.Join(", ", glyphRecords.ConvertAll(r => r.XAdvance.ToString(CultureInfo.InvariantCulture)))} }};");
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const int8_t  {name}_x_offsets[] = {{ {string.Join(", ", glyphRecords.ConvertAll(r => r.XOffset.ToString(CultureInfo.InvariantCulture)))} }};");
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const int8_t  {name}_y_offsets[] = {{ {string.Join(", ", glyphRecords.ConvertAll(r => r.YOffset.ToString(CultureInfo.InvariantCulture)))} }};");
            sb.AppendLine();

            // Struct
            sb.AppendLine("typedef struct {");
            sb.AppendLine("  const uint8_t* const* bitmaps;");
            sb.AppendLine("  const uint8_t*        widths;");
            sb.AppendLine("  const uint8_t*        heights;");
            sb.AppendLine("  const uint8_t*        advances;");
            sb.AppendLine("  const int8_t*         x_offsets;");
            sb.AppendLine("  const int8_t*         y_offsets;");
            sb.AppendLine("  uint16_t              first_char;");
            sb.AppendLine("  uint16_t              last_char;");
            sb.AppendLine("  uint8_t               cell_height;");
            sb.AppendLine("  uint8_t               baseline;");
            sb.AppendLine("  uint8_t               y_advance;");
            sb.AppendLine(CultureInfo.InvariantCulture, $"}} RawFont_{name};");
            sb.AppendLine();

            sb.AppendLine(CultureInfo.InvariantCulture, $"const RawFont_{name} {name}_font = {{");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .bitmaps     = {name}_bitmaps,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .widths      = {name}_widths,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .heights     = {name}_heights,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .advances    = {name}_advances,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .x_offsets   = {name}_x_offsets,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .y_offsets   = {name}_y_offsets,");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .first_char  = 0x{doc.FirstChar:X2},");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .last_char   = 0x{doc.LastChar:X2},");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .cell_height = {doc.CellHeight},");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .baseline    = {doc.Baseline},");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  .y_advance   = {doc.YAdvance}");
            sb.AppendLine("};");

            return sb.ToString();
        }

        private static string GenerateFlipperZero(FontDocument doc, FontExportSettings settings, List<GlyphState> glyphs)
        {
            glyphs = EnsureContiguousGlyphs(doc, glyphs);
            var sb = new StringBuilder();
            string name = SanitiseFontName(settings.FontName);
            string hexFmt = settings.UppercaseHex ? "X2" : "x2";

            sb.AppendLine("// ----------------------------------------------------------------------------");
            sb.AppendLine(CultureInfo.InvariantCulture, $"// Flipper Zero Canvas Font: {name}");
            sb.AppendLine("// Generated by Hexprite - Embedded Pixel Art & Font Editor");
            sb.AppendLine(CultureInfo.InvariantCulture, $"// Dimensions: {doc.MaxCellWidth}x{doc.CellHeight} px | Range: 0x{doc.FirstChar:X2} - 0x{doc.LastChar:X2} | Baseline: {doc.Baseline} px | Y-Advance: {doc.YAdvance} px");
            sb.AppendLine("// ----------------------------------------------------------------------------");

            if (settings.IncludeUsageComment)
            {
                sb.AppendLine("// USAGE GUIDE:");
                sb.AppendLine("// 1. Include this header in your Flipper Zero application or firmware:");
                sb.AppendLine(CultureInfo.InvariantCulture, $"//    #include \"{name}.h\"");
                sb.AppendLine("// 2. Bitmaps are packed in 1-bit column-major format (vertical pages, LSB at top).");
                sb.AppendLine();
            }

            sb.AppendLine("#pragma once");
            sb.AppendLine("#include <stdint.h>");
            sb.AppendLine();

            string upperName = name.ToUpperInvariant();
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define {upperName}_WIDTH {doc.MaxCellWidth}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define {upperName}_HEIGHT {doc.CellHeight}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define {upperName}_FIRST_CHAR 0x{doc.FirstChar:X2}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define {upperName}_LAST_CHAR 0x{doc.LastChar:X2}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define {upperName}_GLYPH_COUNT {glyphs.Count}");
            sb.AppendLine();

            // Bitmap array (column-major, LSB at top)
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_data[] = {{");

            for (int i = 0; i < glyphs.Count; i++)
            {
                var glyph = glyphs[i];
                if (settings.IncludeMetricComments)
                {
                    string charDisp = GetPrintableCharDisplay(glyph.Character);
                    sb.AppendLine(CultureInfo.InvariantCulture, $"  // 0x{glyph.CodePoint:X2} '{charDisp}' ({glyph.Width}x{glyph.Height} px, advance={glyph.XAdvance})");
                }

                if (settings.IncludeGlyphPreview && glyph.Width > 0 && glyph.Height > 0)
                {
                    AppendAsciiPreview(sb, glyph.Pixels, glyph.Width, glyph.Height, "  // ");
                }

                sb.Append("  ");
                int bytesPerCol = (glyph.Height + 7) / 8;
                int pixelLen = glyph.Pixels?.Length ?? 0;
                for (int col = 0; col < glyph.Width; col++)
                {
                    for (int page = 0; page < bytesPerCol; page++)
                    {
                        byte b = 0;
                        for (int bit = 0; bit < 8; bit++)
                        {
                            int row = page * 8 + bit;
                            int pixelIdx = row * glyph.Width + col;
                            if (row < glyph.Height && glyph.Pixels != null && pixelIdx < pixelLen && glyph.Pixels[pixelIdx])
                            {
                                b |= (byte)(1 << bit);
                            }
                        }
                        sb.Append(CultureInfo.InvariantCulture, $"0x{b.ToString(hexFmt, CultureInfo.InvariantCulture)}, ");
                    }
                }
                sb.AppendLine();
            }

            sb.AppendLine("};");
            sb.AppendLine();

            // Character widths array
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_widths[] = {{");
            sb.Append("  ");
            for (int i = 0; i < glyphs.Count; i++)
            {
                sb.Append(CultureInfo.InvariantCulture, $"{glyphs[i].Width}, ");
                if ((i + 1) % 16 == 0 && i < glyphs.Count - 1)
                {
                    sb.AppendLine();
                    sb.Append("  ");
                }
            }
            sb.AppendLine();
            sb.AppendLine("};");
            sb.AppendLine();

            // Character advance array
            sb.AppendLine(CultureInfo.InvariantCulture, $"static const uint8_t {name}_advances[] = {{");
            sb.Append("  ");
            for (int i = 0; i < glyphs.Count; i++)
            {
                sb.Append(CultureInfo.InvariantCulture, $"{glyphs[i].XAdvance}, ");
                if ((i + 1) % 16 == 0 && i < glyphs.Count - 1)
                {
                    sb.AppendLine();
                    sb.Append("  ");
                }
            }
            sb.AppendLine();
            sb.AppendLine("};");

            return sb.ToString();
        }

        private static void AppendAsciiPreview(StringBuilder sb, bool[] pixels, int w, int h, string prefix, string suffix = "")
        {
            if (w == 0 || h == 0 || pixels == null) return;
            for (int y = 0; y < h; y++)
            {
                sb.Append(prefix);
                for (int x = 0; x < w; x++)
                {
                    int idx = y * w + x;
                    sb.Append(idx < pixels.Length && pixels[idx] ? "XX" : "..");
                }
                sb.AppendLine(suffix);
            }
        }

        private struct GlyphRecord
        {
            public int Offset;
            public int Width;
            public int Height;
            public int XAdvance;
            public int XOffset;
            public int YOffset;
        }
    }
}
