using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Hexprite.Core;
using Serilog;

namespace Hexprite.Services
{
    public static class HardwarePreviewSketchGenerator
    {
        public static string GenerateArduinoSketch(HardwarePreviewWiringConfig config, int baudRate)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/*");
            sb.AppendLine("  HexpritePreview-Standalone-Arduino.ino");
            sb.AppendLine("  Generated by Hexprite for " + config.BoardPreset);
            sb.AppendLine("  Display: " + config.DisplayModel + " (" + config.InterfaceType + ")");
            sb.AppendLine("*/");
            sb.AppendLine();
            sb.AppendLine("#include <Arduino.h>");
            sb.AppendLine("#include <U8g2lib.h>");
            sb.AppendLine("#include <Wire.h>");
            sb.AppendLine();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine("//  CONFIGURED HARDWARE PREVIEW SETTINGS");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SERIAL_BAUD {baudRate}");
            sb.AppendLine();

            if (config.InterfaceType == "I2C")
            {
                sb.AppendLine("#define USE_I2C");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define I2C_SDA_PIN   {config.SdaPin.Trim()}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define I2C_SCL_PIN   {config.SclPin.Trim()}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define I2C_ADDRESS   {config.I2cAddress.Trim()}");
                if (config.UseSoftwareI2c)
                {
                    sb.AppendLine("#define USE_SOFTWARE_I2C");
                }
            }
            else
            {
                sb.AppendLine("#define USE_SPI");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_CS_PIN    {config.CsPin.Trim()}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_DC_PIN    {config.DcPin.Trim()}");
                string rstPin = string.IsNullOrWhiteSpace(config.RstPin) ? "U8X8_PIN_NONE" : config.RstPin.Trim();
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_RST_PIN   {rstPin}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_CLK_PIN   {config.ClkPin.Trim()}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_MOSI_PIN  {config.MosiPin.Trim()}");
            }

            sb.AppendLine();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine("//  DISPLAY CONSTRUCTOR");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine(GetConstructorDeclaration(config));
            sb.AppendLine();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine("//  PROTOCOL HANDLER & RUNTIME");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("#if defined(ESP32) || defined(ESP8266) || defined(ARDUINO_ARCH_RP2040) || defined(ARDUINO_ARCH_STM32)");
            sb.AppendLine("  #define MAX_BUFFER 32800");
            sb.AppendLine("#elif defined(__AVR_ATmega2560__)");
            sb.AppendLine("  #define MAX_BUFFER 8200");
            sb.AppendLine("#elif defined(__AVR_ATmega328P__) || defined(__AVR_ATmega168__) || defined(ARDUINO_AVR_UNO) || defined(ARDUINO_AVR_NANO)");
            sb.AppendLine("  #define MAX_BUFFER 1040");
            sb.AppendLine("#else");
            sb.AppendLine("  #define MAX_BUFFER 4200");
            sb.AppendLine("#endif");
            sb.AppendLine("byte buffer[MAX_BUFFER];");
            sb.AppendLine("int bufferIndex = 0;");
            sb.AppendLine("bool packetStarted = false;");
            sb.AppendLine();
            sb.AppendLine("// Diagnostic response codes sent back to Hexprite");
            sb.AppendLine("#define HEXPRITE_ACK_OK         0xA5");
            sb.AppendLine("#define HEXPRITE_ERR_I2C_NACK   0xE1");
            sb.AppendLine("#define HEXPRITE_ERR_CHECKSUM   0xE2");
            sb.AppendLine();
            sb.AppendLine("void setup() {");
            sb.AppendLine("  Serial.begin(SERIAL_BAUD);");
            sb.AppendLine();

            if (config.InterfaceType == "I2C" && !config.UseSoftwareI2c)
            {
                sb.AppendLine("  #if defined(USE_I2C)");
                sb.AppendLine("    #if defined(__AVR__)");
                sb.AppendLine("      Wire.begin();");
                sb.AppendLine("    #elif defined(ESP32) || defined(ESP8266)");
                sb.AppendLine("      Wire.begin(I2C_SDA_PIN, I2C_SCL_PIN);");
                sb.AppendLine("    #elif defined(ARDUINO_ARCH_RP2040) || defined(ARDUINO_ARCH_STM32)");
                sb.AppendLine("      Wire.setSDA(I2C_SDA_PIN);");
                sb.AppendLine("      Wire.setSCL(I2C_SCL_PIN);");
                sb.AppendLine("      Wire.begin();");
                sb.AppendLine("    #else");
                sb.AppendLine("      Wire.begin();");
                sb.AppendLine("    #endif");
                sb.AppendLine();
                sb.AppendLine("    #if defined(WIRE_HAS_TIMEOUT)");
                sb.AppendLine("      Wire.setWireTimeout(25000, true); // 25ms timeout, reset bus on hang");
                sb.AppendLine("    #endif");
                sb.AppendLine("  #endif");
            }

            sb.AppendLine();
            sb.AppendLine("  u8g2.begin();");
            sb.AppendLine("  u8g2.clearBuffer();");
            sb.AppendLine("  u8g2.setFont(u8g2_font_6x10_tf);");
            sb.AppendLine("  u8g2.drawStr(0, 10, \"Hexprite Live\");");
            sb.AppendLine("  u8g2.drawStr(0, 25, \"Waiting for data...\");");
            sb.AppendLine("  u8g2.sendBuffer();");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("void loop() {");
            sb.AppendLine("  while (Serial.available()) {");
            sb.AppendLine("    byte b = Serial.read();");
            sb.AppendLine("    if (!packetStarted) {");
            sb.AppendLine("      if (bufferIndex == 0 && b == 0xAA) {");
            sb.AppendLine("        buffer[bufferIndex++] = b;");
            sb.AppendLine("      } else if (bufferIndex == 1 && b == 0x55) {");
            sb.AppendLine("        buffer[bufferIndex++] = b;");
            sb.AppendLine("        packetStarted = true;");
            sb.AppendLine("      } else {");
            sb.AppendLine("        bufferIndex = (b == 0xAA) ? 1 : 0;");
            sb.AppendLine("        if (bufferIndex == 1) buffer[0] = 0xAA;");
            sb.AppendLine("      }");
            sb.AppendLine("      continue;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    if (bufferIndex >= MAX_BUFFER) {");
            sb.AppendLine("      packetStarted = false;");
            sb.AppendLine("      bufferIndex = 0;");
            sb.AppendLine("      continue;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    buffer[bufferIndex++] = b;");
            sb.AppendLine("    if (bufferIndex >= 6) {");
            sb.AppendLine("      uint16_t w = buffer[2] | (buffer[3] << 8);");
            sb.AppendLine("      uint16_t h = buffer[4] | (buffer[5] << 8);");
            sb.AppendLine("      uint16_t dataSize = ((w + 7) / 8) * h;");
            sb.AppendLine("      uint16_t totalPacketSize = 6 + dataSize + 1;");
            sb.AppendLine();
            sb.AppendLine("      if (totalPacketSize > MAX_BUFFER) {");
            sb.AppendLine("        packetStarted = false;");
            sb.AppendLine("        bufferIndex = 0;");
            sb.AppendLine("        continue;");
            sb.AppendLine("      }");
            sb.AppendLine();
            sb.AppendLine("      if (bufferIndex == totalPacketSize) {");
            sb.AppendLine("        byte calculatedXor = 0;");
            sb.AppendLine("        for (int i = 0; i < totalPacketSize - 1; i++) {");
            sb.AppendLine("          calculatedXor ^= buffer[i];");
            sb.AppendLine("        }");
            sb.AppendLine("        byte receivedXor = buffer[totalPacketSize - 1];");
            sb.AppendLine();
            sb.AppendLine("        if (calculatedXor == receivedXor) {");
            sb.AppendLine("          #if defined(USE_I2C) && !defined(USE_SOFTWARE_I2C)");
            sb.AppendLine("            Wire.beginTransmission(I2C_ADDRESS);");
            sb.AppendLine("            if (Wire.endTransmission() != 0) {");
            sb.AppendLine("              Serial.write(HEXPRITE_ERR_I2C_NACK);");
            sb.AppendLine("              Serial.flush();");
            sb.AppendLine("              packetStarted = false;");
            sb.AppendLine("              bufferIndex = 0;");
            sb.AppendLine("              continue;");
            sb.AppendLine("            }");
            sb.AppendLine("          #endif");
            sb.AppendLine();
            sb.AppendLine("          u8g2.clearBuffer();");
            sb.AppendLine("          u8g2.drawXBM(0, 0, w, h, &buffer[6]);");
            sb.AppendLine("          u8g2.sendBuffer();");
            sb.AppendLine("          Serial.write(HEXPRITE_ACK_OK);");
            sb.AppendLine("          Serial.flush();");
            sb.AppendLine("        } else {");
            sb.AppendLine("          Serial.write(HEXPRITE_ERR_CHECKSUM);");
            sb.AppendLine("          Serial.flush();");
            sb.AppendLine("        }");
            sb.AppendLine("        packetStarted = false;");
            sb.AppendLine("        bufferIndex = 0;");
            sb.AppendLine("      }");
            sb.AppendLine("    }");
            sb.AppendLine("  }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        public static string GetConstructorDeclaration(HardwarePreviewWiringConfig config)
        {
            string model = config.DisplayModel;
            bool isI2c = config.InterfaceType == "I2C";
            bool isSwI2c = isI2c && config.UseSoftwareI2c;

            if (isI2c)
            {
                if (isSwI2c)
                {
                    return model switch
                    {
                        "SSD1306 128x32" =>
                            $"U8G2_SSD1306_128X32_UNIVISION_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ {config.SclPin}, /* data=*/ {config.SdaPin}, /* reset=*/ U8X8_PIN_NONE);",
                        "SH1106 128x64" =>
                            $"U8G2_SH1106_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ {config.SclPin}, /* data=*/ {config.SdaPin}, /* reset=*/ U8X8_PIN_NONE);",
                        "SSD1309 128x64" =>
                            $"U8G2_SSD1309_128X64_NONAME0_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ {config.SclPin}, /* data=*/ {config.SdaPin}, /* reset=*/ U8X8_PIN_NONE);",
                        _ =>
                            $"U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, /* clock=*/ {config.SclPin}, /* data=*/ {config.SdaPin}, /* reset=*/ U8X8_PIN_NONE);"
                    };
                }
                else
                {
                    return model switch
                    {
                        "SSD1306 128x32" =>
                            "U8G2_SSD1306_128X32_UNIVISION_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);",
                        "SH1106 128x64" =>
                            "U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);",
                        "SSD1309 128x64" =>
                            "U8G2_SSD1309_128X64_NONAME0_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);",
                        _ =>
                            "U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);"
                    };
                }
            }
            else // SPI
            {
                string rst = string.IsNullOrWhiteSpace(config.RstPin) ? "U8X8_PIN_NONE" : config.RstPin;
                return model switch
                {
                    "SSD1306 128x32" =>
                        $"U8G2_SSD1306_128X32_UNIVISION_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ {config.CsPin}, /* dc=*/ {config.DcPin}, /* reset=*/ {rst});",
                    "SH1106 128x64" =>
                        $"U8G2_SH1106_128X64_NONAME_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ {config.CsPin}, /* dc=*/ {config.DcPin}, /* reset=*/ {rst});",
                    "SSD1309 128x64" =>
                        $"U8G2_SSD1309_128X64_NONAME0_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ {config.CsPin}, /* dc=*/ {config.DcPin}, /* reset=*/ {rst});",
                    "ST7920 128x64" =>
                        $"U8G2_ST7920_128X64_F_HW_SPI u8g2(U8G2_R0, /* cs=*/ {config.CsPin}, /* reset=*/ {rst});",
                    _ =>
                        $"U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ {config.CsPin}, /* dc=*/ {config.DcPin}, /* reset=*/ {rst});"
                };
            }
        }

        public static string GenerateLibrarySnippet(HardwarePreviewWiringConfig config, int baudRate = 115200)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// === Hexprite Live Hardware Preview Integration ===");
            sb.AppendLine("#include <U8g2lib.h>");
            if (config.InterfaceType == "I2C") sb.AppendLine("#include <Wire.h>");
            sb.AppendLine("#include <HexpritePreview.h>");
            sb.AppendLine();
            sb.AppendLine("// 1. Display constructor for " + config.DisplayModel + ":");
            sb.AppendLine(GetConstructorDeclaration(config));
            sb.AppendLine();
            sb.AppendLine("// 2. Hardware preview helper object:");
            sb.AppendLine("HexpritePreview hexpritePreview;");
            sb.AppendLine();
            sb.AppendLine("void setup() {");
            sb.AppendLine(CultureInfo.InvariantCulture, $"  Serial.begin({baudRate});");
            if (config.InterfaceType == "I2C" && !config.UseSoftwareI2c)
            {
                sb.AppendLine("  // Remap I2C pins if supported:");
                sb.AppendLine("  #if defined(ESP32) || defined(ESP8266)");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    Wire.begin({config.SdaPin}, {config.SclPin});");
                sb.AppendLine("  #elif defined(ARDUINO_ARCH_RP2040) || defined(ARDUINO_ARCH_STM32)");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    Wire.setSDA({config.SdaPin});");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    Wire.setSCL({config.SclPin});");
                sb.AppendLine("    Wire.begin();");
                sb.AppendLine("  #endif");
            }
            sb.AppendLine("  u8g2.begin();");
            sb.AppendLine("  hexpritePreview.begin(u8g2);");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("void loop() {");
            sb.AppendLine("  hexpritePreview.update(); // Checks for live serial frames from Hexprite");
            sb.AppendLine("  // ... your project code ...");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static List<WirePinMapping> GetWireMapping(HardwarePreviewWiringConfig config)
        {
            var list = new List<WirePinMapping>();

            if (config.InterfaceType == "I2C")
            {
                list.Add(new WirePinMapping { DisplayPin = "VCC", BoardPin = "3.3V / 5V", Description = "Power supply", WireColor = "Red" });
                list.Add(new WirePinMapping { DisplayPin = "GND", BoardPin = "GND", Description = "Ground reference", WireColor = "DimGray" });
                list.Add(new WirePinMapping { DisplayPin = "SDA / D1", BoardPin = config.SdaPin, Description = "Serial Data Line", WireColor = "Gold" });
                list.Add(new WirePinMapping { DisplayPin = "SCL / D0", BoardPin = config.SclPin, Description = "Serial Clock Line", WireColor = "DeepSkyBlue" });
            }
            else // SPI
            {
                list.Add(new WirePinMapping { DisplayPin = "VCC", BoardPin = "3.3V / 5V", Description = "Power supply", WireColor = "Red" });
                list.Add(new WirePinMapping { DisplayPin = "GND", BoardPin = "GND", Description = "Ground reference", WireColor = "DimGray" });
                list.Add(new WirePinMapping { DisplayPin = "CS", BoardPin = config.CsPin, Description = "Chip Select", WireColor = "Orange" });
                list.Add(new WirePinMapping { DisplayPin = "DC", BoardPin = config.DcPin, Description = "Data / Command control", WireColor = "LimeGreen" });
                list.Add(new WirePinMapping { DisplayPin = "RST", BoardPin = string.IsNullOrWhiteSpace(config.RstPin) ? "None (or 3.3V)" : config.RstPin, Description = "Reset line", WireColor = "White" });
                list.Add(new WirePinMapping { DisplayPin = "D0 / SCK", BoardPin = config.ClkPin, Description = "SPI Clock", WireColor = "DeepSkyBlue" });
                list.Add(new WirePinMapping { DisplayPin = "D1 / MOSI", BoardPin = config.MosiPin, Description = "SPI Master-Out-Slave-In", WireColor = "Gold" });
            }

            return list;
        }

        public static bool UpdateStandaloneSketchInAppData(HardwarePreviewWiringConfig config, int baudRate)
        {
            try
            {
                // Always write to the user's AppData directory (writable), not the install directory.
                string standaloneDir = Path.Combine(AssetsPathService.AppDataAssetsDirectory, AssetsPathService.HexpritePreviewStandaloneFolderName);

                if (!Directory.Exists(standaloneDir))
                {
                    Directory.CreateDirectory(standaloneDir);
                }

                string targetFile = Path.Combine(standaloneDir, AssetsPathService.StandaloneSketchFileName);
                string sketch = GenerateArduinoSketch(config, baudRate);
                SafeFileIo.WriteAllTextAtomic(targetFile, sketch, maxRetries: 3);
                return true;
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Failed to update standalone sketch in AppData");
                return false;
            }
        }

        public static string GeneratePlatformIOConfig(HardwarePreviewWiringConfig config, int baudRate)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/*");
            sb.AppendLine(" * config.h — Hexprite Live Hardware Preview Configuration");
            sb.AppendLine(" * Generated by Hexprite for " + config.BoardPreset);
            sb.AppendLine(" */");
            sb.AppendLine();
            sb.AppendLine("#pragma once");
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SERIAL_BAUD {baudRate}");
            sb.AppendLine();
            if (config.InterfaceType == "I2C")
            {
                sb.AppendLine("#define USE_I2C");
                sb.AppendLine("// #define USE_SPI");
            }
            else
            {
                sb.AppendLine("// #define USE_I2C");
                sb.AppendLine("#define USE_SPI");
            }
            sb.AppendLine();
            sb.AppendLine("// I2C Configuration");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define I2C_SDA_PIN   {config.SdaPin.Trim()}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define I2C_SCL_PIN   {config.SclPin.Trim()}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define I2C_ADDRESS   {config.I2cAddress.Trim()}");
            if (config.UseSoftwareI2c)
            {
                sb.AppendLine("#define USE_SOFTWARE_I2C");
            }
            sb.AppendLine();
            sb.AppendLine("// SPI Configuration");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_CS_PIN    {config.CsPin.Trim()}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_DC_PIN    {config.DcPin.Trim()}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_RST_PIN   {(string.IsNullOrWhiteSpace(config.RstPin) ? "U8X8_PIN_NONE" : config.RstPin.Trim())}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_CLK_PIN   {config.ClkPin.Trim()}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define SPI_MOSI_PIN  {config.MosiPin.Trim()}");
            sb.AppendLine();
            sb.AppendLine("// Display Model");
            string defineName = GetPlatformIODisplayDefine(config.DisplayModel, config.InterfaceType);
            sb.AppendLine(CultureInfo.InvariantCulture, $"#define {defineName}");
            sb.AppendLine();
            return sb.ToString();
        }

        private static string GetPlatformIODisplayDefine(string displayModel, string interfaceType)
        {
            string suffix = interfaceType == "SPI" ? "SPI" : "I2C";
            return displayModel switch
            {
                "SSD1306 128x32" => $"DISPLAY_SSD1306_128X32_{suffix}",
                "SH1106 128x64" => $"DISPLAY_SH1106_128X64_{suffix}",
                "SSD1309 128x64" => $"DISPLAY_SSD1309_128X64_{suffix}",
                "ST7920 128x64" => "DISPLAY_ST7920_128X64_SPI",
                _ => $"DISPLAY_SSD1306_128X64_{suffix}"
            };
        }

        public static string GeneratePlatformIOIni(string boardPreset, int baudRate)
        {
            string defaultEnv = boardPreset switch
            {
                "ESP32 DevKit" => "esp32",
                "Arduino Mega" => "mega",
                "Arduino Uno / Nano" => "uno",
                "Raspberry Pi Pico (RP2040)" => "pico",
                "STM32 Blue Pill" => "bluepill",
                "ESP8266 NodeMCU / D1 Mini" => "esp8266",
                _ => "uno"
            };

            var sb = new StringBuilder();
            sb.AppendLine("; ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine(";  HexpritePreview-Standalone-PlatformIO — PlatformIO Configuration");
            sb.AppendLine(";  Auto-configured for " + boardPreset);
            sb.AppendLine("; ═══════════════════════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("[platformio]");
            sb.AppendLine(CultureInfo.InvariantCulture, $"default_envs = {defaultEnv}");
            sb.AppendLine();
            sb.AppendLine("[common]");
            sb.AppendLine("lib_deps =");
            sb.AppendLine("    olikraus/U8g2@^2.35.30");
            sb.AppendLine(CultureInfo.InvariantCulture, $"monitor_speed = {baudRate}");
            sb.AppendLine("framework = arduino");
            sb.AppendLine();
            sb.AppendLine("[env:uno]");
            sb.AppendLine("platform = atmelavr");
            sb.AppendLine("board = uno");
            sb.AppendLine("framework = ${common.framework}");
            sb.AppendLine("lib_deps = ${common.lib_deps}");
            sb.AppendLine("monitor_speed = ${common.monitor_speed}");
            sb.AppendLine();
            sb.AppendLine("[env:esp32]");
            sb.AppendLine("platform = espressif32");
            sb.AppendLine("board = esp32dev");
            sb.AppendLine("framework = ${common.framework}");
            sb.AppendLine("lib_deps = ${common.lib_deps}");
            sb.AppendLine("monitor_speed = ${common.monitor_speed}");
            sb.AppendLine();
            sb.AppendLine("[env:mega]");
            sb.AppendLine("platform = atmelavr");
            sb.AppendLine("board = megaatmega2560");
            sb.AppendLine("framework = ${common.framework}");
            sb.AppendLine("lib_deps = ${common.lib_deps}");
            sb.AppendLine("monitor_speed = ${common.monitor_speed}");
            sb.AppendLine();
            sb.AppendLine("[env:pico]");
            sb.AppendLine("platform = raspberrypi");
            sb.AppendLine("board = pico");
            sb.AppendLine("framework = ${common.framework}");
            sb.AppendLine("lib_deps = ${common.lib_deps}");
            sb.AppendLine("monitor_speed = ${common.monitor_speed}");
            sb.AppendLine();
            sb.AppendLine("[env:bluepill]");
            sb.AppendLine("platform = ststm32");
            sb.AppendLine("board = bluepill_f103c8");
            sb.AppendLine("framework = ${common.framework}");
            sb.AppendLine("lib_deps = ${common.lib_deps}");
            sb.AppendLine("monitor_speed = ${common.monitor_speed}");
            sb.AppendLine("upload_protocol = stlink");
            sb.AppendLine();
            sb.AppendLine("[env:esp8266]");
            sb.AppendLine("platform = espressif8266");
            sb.AppendLine("board = nodemcuv2");
            sb.AppendLine("framework = ${common.framework}");
            sb.AppendLine("lib_deps = ${common.lib_deps}");
            sb.AppendLine("monitor_speed = ${common.monitor_speed}");
            return sb.ToString();
        }

        public static bool UpdatePlatformIOConfigInAppData(HardwarePreviewWiringConfig config, int baudRate)
        {
            try
            {
                string pioRoot = Path.Combine(AssetsPathService.AppDataAssetsDirectory, AssetsPathService.HexpritePreviewPlatformIOFolderName);
                string pioSrc = Path.Combine(pioRoot, "src");
                Directory.CreateDirectory(pioSrc);

                string cfgFile = Path.Combine(pioSrc, "config.h");
                string cfgContent = GeneratePlatformIOConfig(config, baudRate);
                SafeFileIo.WriteAllTextAtomic(cfgFile, cfgContent, maxRetries: 3);

                string iniFile = Path.Combine(pioRoot, "platformio.ini");
                string iniContent = GeneratePlatformIOIni(config.BoardPreset, baudRate);
                SafeFileIo.WriteAllTextAtomic(iniFile, iniContent, maxRetries: 3);

                return true;
            }
            catch (Exception ex)
            {
                Log.Warning(ex, "Failed to update PlatformIO config in AppData");
                return false;
            }
        }
    }
}
